In [1]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler

X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = Perceptron()
clf.fit(X, y)
predictions = clf.predict(X)


scaler = StandardScaler()
X_train = np.array([[100.0, 2.0], [50.0, 4.0], [70.0, 6.0]])
X_test = np.array([[90.0, 1], [40.0, 3], [60.0, 4]])
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

[0 0 0]
[[ 100.    2.]
 [  50.    4.]
 [  70.    6.]]
[[ 1.29777137 -1.22474487]
 [-1.13554995  0.        ]
 [-0.16222142  1.22474487]]


In [81]:
import pandas as pd
from sklearn.metrics import accuracy_score

train = pd.read_csv('perceptron-train.csv', header = None)
X_train = train.iloc[:, 1:3]
y_train = train[0]
test = pd.read_csv('perceptron-test.csv', header = None)
X_test = test[[1, 2]]
y_test = test[0]

clf = Perceptron(random_state=241)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

scaled = StandardScaler()
X_train_sc = scaler.fit_transform(X_train) # use fit_transform to train set and transform to testset
X_test_sc = scaler.transform(X_test)
clf = Perceptron(random_state=241)
clf.fit(X_train_sc, y_train)
y_pred_sc = clf.predict(X_test_sc)
acc_sc = accuracy_score(y_test, y_pred_sc)
ans = acc_sc - acc
str(acc_sc - acc)
with open('q5.txt', 'w') as f:
    f.write(str(ans))
f.close()